name: CI
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install texlive
        run: sudo apt install texlive-base 
      - name: Install texlive-latex-extra
        run: sudo apt-get install texlive-latex-extra texlive-fonts-extra texlive-xetex 
      - name: Build pdf
        run: xelatex Jonathan_Heidegger_Resume.tex 
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: Jonathan_Heidegger_Resume.pdf
